version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./application/:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      APACHE_SERVER_NAME: ba_laravel
      APPLICATION_ENV: development
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
    container_name: ba_laravel_task
    links:
      - db
    networks:
      - web

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ba_laravel
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    networks:
      - web

  mailhog_server:
    container_name: cont_mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - web

networks:
  web: